package com.internship.RecruitmentManagementSystem.RecruitmentManagementSystem.repositories;

import com.internship.RecruitmentManagementSystem.RecruitmentManagementSystem.models.model.PositionRequirementModel;
import org.springframework.data.jpa.repository.JpaRepository;

public interface PositionRequirementRepository extends JpaRepository<PositionRequirementModel,Integer> {
}
