package com.internship.RecruitmentManagementSystem.RecruitmentManagementSystem.repositories;

import com.internship.RecruitmentManagementSystem.RecruitmentManagementSystem.models.model.ShortlistedApplicationStatusModel;
import org.springframework.data.jpa.repository.JpaRepository;

public interface ShortlistedApplicationStatusRepository extends JpaRepository<ShortlistedApplicationStatusModel,Integer> {
}
